const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SubInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{menubg: 0},
	{Text: 0},
	{Quit: 0},
	{Play: 0},
	{Platform: 0},
	{DestroyOutsideLayout: 0},
	{Joe: 0},
	{Solid: 0},
	{GroundLvl1: 0},
	{LineOfSight: 0},
	{Hat_trooper: 0},
	{Sine: 0},
	{Spiber: 0},
	{Spike: 0},
	{DoritoOfTime: 0},
	{Sprite: 0},
	{Level2Ground: 0},
	{lava: 0},
	{VolcanicBg: 0},
	{SoldierGuy: 0},
	{Blob: 0},
	{templeGround: 0},
	{templebg: 0},
	{Sprite2: 0},
	{DeathCheezs: 0},
	{Hellground: 0},
	{hellbg: 0},
	{HEALTH: 0},
	{GeneralObesious: 0},
	{Bullet: 0},
	{DAGGER: 0},
	{DestroyOutside: 0},
	{Spear: 0},
	{Gamemode: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	menubg: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Quit: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Joe: class extends self.ISpriteInstance {},
	GroundLvl1: class extends self.ISpriteInstance {},
	Hat_trooper: class extends self.ISpriteInstance {},
	Spiber: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	DoritoOfTime: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Level2Ground: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	VolcanicBg: class extends self.ISpriteInstance {},
	SoldierGuy: class extends self.ISpriteInstance {},
	Blob: class extends self.ISpriteInstance {},
	templeGround: class extends self.ISpriteInstance {},
	templebg: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	DeathCheezs: class extends self.ISpriteInstance {},
	Hellground: class extends self.ISpriteInstance {},
	hellbg: class extends self.ISpriteInstance {},
	GeneralObesious: class extends self.ISpriteInstance {},
	DAGGER: class extends self.ISpriteInstance {},
	Spear: class extends self.ISpriteInstance {}
}